### ISSUE TITLE
Trinket app fails to load

### ISSUE THREAD

**Issue by Jonic** [raspberrypilearning/codecraft#1]
On the introduction step, the Trinket app fails with a Python error:

`TypeError: register_shape() takes exactly 2 positional argument(s) (1 given) on line 284 in main.py`

**Comment by rik-cross** [comment]
Trinket are aware and pushing a fix as we speak. I'll close this issue when the fix is live.

**Comment by rik-cross** [comment]
FYI -- this also affects Robo-Trumps:
https://github.com/raspberrypilearning/robo-trumps

**Comment by rik-cross** [comment]
This has now been fixed -- thanks for raising @Jonic!
