### ISSUE TITLE
Outstanding commits

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/codecraft#31]
@ninaszymor 

there are outstanding commits in draft, can they be pushed to master?

**Comment by ninaszymor** [comment]
@martinohanlon I can't see any commits from me, am I missing something?

**Comment by martinohanlon** [comment]
@ninaszymor there is an open PR - https://github.com/raspberrypilearning/codecraft/pull/4

**Comment by ninaszymor** [comment]
@martinohanlon that's on a different branch (l10n master); these commits are not ready to be merged into master, I'm afraid.

**Comment by martinohanlon** [comment]
@ninaszymor ok - when you do merge you might get conflicts, but thats always a risk.
