### ISSUE TITLE
Screenshots inconsistent with code (Feb 2019)

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/codecraft#44]
The screenshots in step 2 show the labels [dirt] [grass] [water] [brick] but when you run the code in the starter trinket, these labels don't exist.

**Comment by libxx1** [comment]
@rik-cross I can go through and update the screenshots to remove labels but just checking to see if that's the way we want to go rather than adding them to the trinket?

**Comment by rik-cross** [comment]
Hi @libxx1 -- it's up to you. If you think the labels are useful I've added them to a version of the code here:
https://trinket.io/embed/python/d51a810bec
You'd have to replace the main .py file in the trinket, resources and solutions.

If you don't think it's worth it, then feel free to just edit the screenshots.

Thanks!
